[phases.setup]
nixPkgs = ["php82", "php82Extensions.pdo", "php82Extensions.pdo_mysql", "php82Extensions.mbstring", "php82Extensions.zip", "php82Extensions.gd", "php82Extensions.dom", "php82Extensions.curl", "php82Extensions.xml", "php82Extensions.tokenizer"]

[phases.install]
cmds = [
    "curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer",
    "composer install --optimize-autoloader --no-dev --no-interaction"
]

[phases.build]
cmds = ["php artisan config:clear"]

[start]
cmd = "php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT"
