[build]
builder = "NIXPACKS"

[deploy]
startCommand = "php artisan migrate --force && php artisan db:seed --class=AdminUserSeeder --force && php artisan serve --host=0.0.0.0 --port=$PORT --env=production"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
